[project]
name = "shl"
version = "0.0.0"

[project.optional-dependencies]
dev = [
    "pytest",
]

[project.scripts]
shl = "shl:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
